server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://azz34.mysql.pythonanywhere-services.com:3306/azz34$authdb?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: azz34
    password: turnos-12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

app:
  cors:
    allowed-origins: "http://localhost:5173,http://localhost:3000"

security:
  jwt:
    issuer: "auth-service"          # ⬅ Debe coincidir con el que exige catalog-service
    access-token-minutes: 30
    refresh-token-days: 7
    key:
      private-path: "keys/private_key.pem"  # ⬅ En classpath: src/main/resources/keys/...
      public-path:  "keys/public_key.pem"

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
